---
title:               Scott's Blog
tagline:             Think Inside the Block.
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "username" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "password" %>
name:                Scott Block
twitter:             insidetheblock
github:              scottrblock
email:               scott@scottblock.com
google_analytics_id: UA-33713468-1